package com.chitfund.repository;

import com.chitfund.model.ChitPlan;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface ChitPlanRepository extends JpaRepository<ChitPlan, Long> {
    // save(), findAll(), existsById(), deleteById()
    // — all auto-generated by JpaRepository. Nothing else needed here.
}