# Server
server.port=8080

# SQLite
spring.datasource.url=jdbc:sqlite:database/chitfund.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none