server.port=8080

spring.datasource.url=jdbc:postgresql://chitfund_db_10k2_user:TvpRyK9xtQyMgJ1Cm2d8nDNFTBi3FhFH@dpg-d7pjplb7uimc73b492ug-a/chitfund_db_10k2
spring.datasource.username=chitfund_db_10k2_user
spring.datasource.password=TvpRyK9xtQyMgJ1Cm2d8nDNFTBi3FhFH
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect