# Server
server.port=8080

# SQLite - single database
spring.datasource.url=jdbc:sqlite:/app/database/admin.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update